

# BrieFlow cluster configuration file

default-resources:
    slurm_partition: 20
    slurm_account: wibrusers
    mem_mb: 3000
    tasks: 1
    cpus_per_task: 1
    runtime: 400
    slurm_extra: "'--output=slurm/slurm_output/rule/%j.out'"
jobs: 150

set-resources:
   # preprocessing
    extract_metadata_sbs:
        mem_mb: 2000
    combine_metadata_sbs:
        mem_mb: 2500
    extract_metadata_phenotype:
        mem_mb: 2000
    combine_metadata_phenotype:
        mem_mb: 2500
    convert_sbs:
        mem_mb: 2000
    convert_ph:
        mem_mb: 2000
    calculate_ic_sbs:
        mem_mb: 50000
    calculate_ic_phenotype:
        mem_mb: 500000

    # sbs
    align_sbs:
        mem_mb: 2500
    log_filter:
        mem_mb: 2500
    compute_standard_deviation:
        mem_mb: 2500
    find_peaks:
        mem_mb: 2000
    max_filter:
        mem_mb: 2000
    apply_ic_field_sbs:
        mem_mb: 2500
    segment_sbs:
        # slurm_partition: "'nvidia-2080ti-20'"
        mem_mb: 3500
        cpus_per_task: 4
        # slurm_extra: "'--gres=gpu:1'"
    extract_bases:
        mem_mb: 2000
    call_reads:
        mem_mb: 1500
    call_cells:
        mem_mb: 1500
    extract_sbs_info:
        mem_mb: 2000
    combine_reads:
        mem_mb: 20000
    combine_cells:
        mem_mb: 20000
    combine_sbs_info:
        mem_mb: 20000
    eval_segmentation_sbs:
        mem_mb: 50000
    eval_mapping:
        mem_mb: 50000
        cpus_per_task: 12

    # phenotype
    apply_ic_field_phenotype:
        mem_mb: 2000
    align_phenotype:
        mem_mb: 2000
    segment_phenotype:
        # slurm_partition: "'nvidia-2080ti-20'"
        mem_mb: 3000
        cpus_per_task: 4
        # slurm_extra: "'--gres=gpu:1'"
    identify_cytoplasm:
        mem_mb: 1000
    extract_phenotype_info:
        mem_mb: 1000
    combine_phenotype_info:
        mem_mb: 20000
    extract_phenotype_cp:
        mem_mb: 3000
    merge_phenotype_cp:
        mem_mb: 300000
    eval_segmentation_phenotype:
        mem_mb: 50000
    eval_features:
        mem_mb: 4000

    # merge
    fast_alignment:
        mem_mb: 20000
        cpus_per_task: 4
    merge:
        mem_mb: 20000
        cpus_per_task: 4
    format_merge:
        mem_mb: 20000
    eval_merge:
        mem_mb: 20000
    clean_merge:
        mem_mb: 20000
    deduplicate_merge:
        mem_mb: 20000
        cpus_per_task: 4
    final_merge:
        mem_mb: 500000

    # aggregate
    split_datasets:
        mem_mb: 200000
    filter:
        mem_mb: 100000
    generate_feature_table:
        mem_mb: 980000
        cpus_per_task: 4
    align:
        mem_mb: 980000
        cpus_per_task: 4
    aggregate:
        mem_mb: 980000
        cpus_per_task: 4
    eval_aggregate:
        mem_mb: 980000
        cpus_per_task: 4
    # montages
    prepare_montage_data:
        mem_mb: 100000
        cpus_per_task: 8
    generate_montage:
        mem_mb: 10000
    initiate_montage:
        mem_mb: 1000

    # cluster
    clean_aggregate:
        mem_mb: 2000
    phate_leiden_clustering:
        mem_mb: 10000
    benchmark_clusters:
        mem_mb: 10000
