blank_issues_enabled: false
contact_links:
  - name: Brieflow Issues
    url: https://github.com/cheeseman-lab/brieflow/issues
    about: Nearly all issues (env issues, library bugs, etc) should be reported in the brieflow repository.
  - name: Brieflow Community
    url: https://discord.gg/yrEh6GP8JJ
    about: Join the Brieflow Discord to ask questions, share ideas, and get help from other users and developers.
